coriolis/utils.py
This should fix the intermittent lock-ups we have been seeing during OSMorphing.
=> Disable pipelined transfers for SFTP

coriolis/osmorphing/manager.py, coriolis/osmorphing/osmount/base.py
In some situations, during os morphing, some binaries that get called
inside the chroot, may mount aditional filesystems, as a child of some
already mounted FS. For example, some applications that require FUSE
may mount aditional kernel filesystems in /sys. This change unmounts
child filesystems before attempting to unmount parent filesystems.
This is done by looking in /proc/mounts first, sorting the mounts that
have the root filesystem as a prefix, and unmounting them in order.
NOTE: currently testing this.
=> Fix os_dismount()

.gitattributes, coriolis/db/sqlalchemy/migrate_repo/versions/009_Migrate_info_to_blob.py, coriolis/db/sqlalchemy/models.py, coriolis/db/sqlalchemy/types.py, coriolis/providers/backup_readers.py, coriolis/providers/backup_writers.py, coriolis/providers/replicator.py, coriolis/secrets.py, coriolis/utils.py, coriolis/worker/rpc/server.py, requirements.txt
This PR adds/fixes the following:
* Adds replicator integration. The replicator is an implementation of a disk differentiating procedure that allows us to have replicas even for providers that do not have a native way of getting incremental diffs of storage devices.
* Replicator listens on default port 4433.
* Replicator implements a ssh tunnel fallback in case 4433 is not directly accessible
* During initial replica, if destination provider zeros out disks before attaching them to instances, only written blocks will be transfered.
* on subsequent replica runs, any changes (even zero chunks) are synced.
* fixes a deadlock in coriolis core which shows up when task_info is larger than can be put on a linux named pipe.
* changes the info field of ```base_transfer_action``` to ```LONGBLOB```
=> Add replicator integration

coriolis/osmorphing/base.py, coriolis/osmorphing/suse.py
Considering `zypper` does not have an `--ignore-missing`-type flag, and
returns a non-zero exit code when a package it's trying to uninstall is
missing, Coriolis will now silently skip any uninstallation issues on
SLES.
=> Ignore Exceptions while uninstalling packages on SUSE.

coriolis/providers/backup_writers.py, coriolis/providers/replicator.py
Currently, compression is enabled by default, and there is no way to disable it via config or from the providers calling SSHBackupWriter. This PR adds the ability to do both.
=> Make compression configurable

coriolis/wsman.py
TLS 1.0 is broken and a lot of servers have disabled it. This sets TLS 1.2 in powershell before calling download.
=> Enable TLS1.2 in download_file

coriolis/conductor/rpc/server.py
In case of Replicas which did not have a Reservation ID created for
them, skip the reservation check.
=> Skip checking reservations on missing `reservation_id`

coriolis/conductor/rpc/server.py
The replica source inputs validation task does not
need anything from the get instance info task.
Thus, the tasks dependency is redundant.
=> Remove redundant task dependency

coriolis/providers/backup_writers.py, coriolis/schemas.py, coriolis/schemas/disk_sync_resources_conn_info_schema.json, coriolis/schemas/disk_sync_resources_info_schema.json, coriolis/schemas/os_morphing_resources_schema.json, coriolis/schemas/vm_export_info_schema.json, coriolis/schemas/volumes_info_schema.json, coriolis/tasks/migration_tasks.py, coriolis/tasks/replica_tasks.py
Coriolis-core will not both validate the schema of the returned 'volumes_info' of each Replica task, as well as reorder the returned volumes into to match the exact ordering found in `export_info[devices][disks]`.
Also added dedicated schemas for the disk sync resources.
Added the following schemas:
- disk_sync_resources_conn_info_schema.json -- for defining SSH connection params for temporary minion VMs
- disk_sync_resources_info_schema.json -- schema defining volumes_info for disk syncing (both for Migrations and Replicas)
Tested import providers which showed signs of potential disk ordering issues:
=> Ensure disk ordering is preserved during Replication.

coriolis/providers/replicator.py
This makes use of utils.create_service() and refactors a bit the way certificates are copied over from the replicator.
Depends on #46
=> Cleanup replicator integration

coriolis/keystone.py
* Use `IntOpt` for the `identity_api_version` config option
* Fix create_keystone_session method. When using the `v3token` plugin, the `user_domain_name` or
`user_domain_id` must not be set, otherwise the following error is thrown when creating the Keystone v3 session:
```
Exception during message handling:
TypeError: __init__() got an unexpected keyword argument 'user_domain_name'
```
However, `user_domain_name` or `user_domain_id` are required when using other auth plugins (for example, the `v3password` plugin).
=> Fix Keystone v3 session

coriolis/providers/backup_writers.py
Leverage a HTTP based backup writer. The HTTP backup writer has the added benefit of requiring less resources for large chunks, as it does not need to rely on struct.pack to generate the payload it sends over the wire. Standard HTTP calls are made to a remote API.
It also does not require a live, SSH channel to be active, and recovery from failure is more likely to succeed. Removing the reliance on paramiko also means that we are no longer constrained by the fact that encryption of data over SSH done by paramiko is single threaded and limited by the power of a single core available to the Coriolis  worker.
It's worth noting that this also implements queueing for the phases of transfer of data from source to destination. There is a ```compression``` queue, and a ```sender``` queue. That …
=> Add http backup writer

coriolis/osmorphing/base.py, coriolis/osmorphing/coreos.py, coriolis/osmorphing/debian.py, coriolis/osmorphing/openwrt.py, coriolis/osmorphing/redhat.py, coriolis/osmorphing/suse.py, coriolis/utils.py
This change does the following:
For situations where replicas are created with ```set_dhcp=True```:
* Disable predictable NIC names
* Create DHCP enabled configs for all NICs
* Make backups of any mutated config files
When migrating from one cloud to another and from one hypervisor to another, there is no way to guarantee NIC names will stay the same on the destination. The only condition where we can ensure NIC names, is if the cloud allows us to preserve both MAC addresses and IP addresses when migrating from source.
It also means the source allows us to introspect the instance using the cloud APIs and fetch the required info. Given that we currently only have a small nr of combinations where this would work, flattening the morphing procedure for networking is the only sane approach, …
=> Refactor network morphing

coriolis/osmorphing/base.py, coriolis/osmorphing/redhat.py
Adds _set_selinux_autorelabel() to Linux OS morphers, that when called, will instruct the target system to relabel files on the root partition.
=> Add _set_selinux_autorelabel()

coriolis/schemas/vm_export_info_schema.json
While this mixup doesn't directly functionality (the plugins still put the field in the right place), it warrants fixing for the API to be in line with the schema.
=> Move 'public_ip_address' out of the 'devices' list in the VM info schema.

.gitignore, coriolis/providers/backup_writers.py, coriolis/providers/replicator.py, coriolis/resources/makefile, coriolis/utils.py
Move the static binaries from the `resources` directory
to `resources/bin` directory.
This is useful when running the Coriolis service into a
container, as `resources/bin` can be used as a mount point
with the binaries separately built.
=> Add resources/bin directory

coriolis/tasks/replica_tasks.py
Avoid logging the replicator state.
=> Redact volume_info when replicatoris used

coriolis/conductor/rpc/server.py
This patch makes the conductor schedule the VALIDATE_SOURCE_*_INPUTS
tasks before the GET_INSTANCE_INFO ones of both Migrations and Replicas.
This is so as to allow the source validation to run before the instance
query (which might depend on params validated by the former), as well as
prevent any state conflicts while the two tasks are running.
=> Schedule VALIDATE_SOURCE tasks before GET_INSTANCE.

coriolis/osmorphing/osmount/windows.py
On older Windows systems there is no Update-HostStorageCache
commandlet. This replaces the powershell rescan with a diskpart
equivalent.
=> Fix storage rescan

coriolis/osmorphing/osmount/windows.py
This works on all versions of Windows. It makes sense to have one common way to do this.
=> Use diskpart to bring basic disks online

coriolis/utils.py
Most of the commands sent through SSH require root privileges, which
we have to send through pseudo-terminal. Unfortunately, the pty outputs
an additional '\r' to every newline. This may affect some plugins too.
By replacing '\r\n' with '\n', the outputs should be the same as
before using pseudo-terminal.
=> Fix pseudo-terminal command output

coriolis/osmorphing/manager.py
The original exception can be quite large and useless to the user.
This wraps the original exception in a more user friendly error
message. It should present a more informative message to the user
while still outputing useful debug info in the logs.
=> Return a more friendly exception

.gitignore, coriolis/osmorphing/windows.py, coriolis/resources/bin/bring-disks-online.ps1
Add a common way to install cloudbase-init across all providers. Each provider can customize some aspects of the cloudbase-init config like the metadata service to use, the plugins that should be enabled and the local scripts that should be copied over.
=> Abstract cbsl init install

coriolis/conductor/rpc/server.py
Due to flawed logic, on_error tasks which were in ERROR/COMPLETED state could prevent the whole execution from being marked as 'ERROR'd.
=> Prevent execution status locking from on_error tasks.

coriolis/data_transfer.py, coriolis/providers/backup_writers.py
This should speed up the transfer speed when using the SSH backup
writer. Currently, there are 3 operations that happen:
1) Read from the source
2) Compress and encode payload
3) Send payload to destination
These 3 operations run in sequence for each chunk, which means that
while we are reading from the source, we are not compressing or
sending. While we are compressing and encoding, we are not reading
from the source or sending to destination, etc. Using queues allows
us to do more work in parallel.
=> Use queueing for SSH backup writer

coriolis/api/v1/migrations.py, coriolis/api/v1/replicas.py, coriolis/api/v1/utils.py, coriolis/api/v1/views/migration_view.py, coriolis/conductor/rpc/client.py, coriolis/conductor/rpc/server.py, coriolis/db/api.py, coriolis/db/sqlalchemy/models.py
In an effort to make available the soft-deleted migrations and replicas to the API consumer, this branch also includes various fixes that needed to be implemented before we could achieve the desired result. As such, as part of this PR, there is also a slightly reworked way of returning results from the conductor to the API server, in a way that avoids serializing a potentially huge object, that includes task_info.
=> Show deleted migrations/replicas

coriolis/osmorphing/osmount/base.py
The entries in fstab used to be mounted in the order they appear in.
This can lead to situations where parent mountpoints later in the file
override child mountpoints earlier in it (e.g. /var/log/mysql can be
overriden by mounting /var/log afterwards)
=> Mount fstab entries in the correct order.

coriolis/conductor/rpc/server.py
Given that the VALIDATE_SOURCE_INPUTS and GET_INSTANCE_INFO tasks run
independently, an extra dependency must be declared for the
DEPLOY_MIGRATION_SOURCE_RESOURCES to the GET_INSTANCE_INFO task to
ensure that the 'export_info' will be available.
=> Fix task deps for DEPLOY_MIGRATION_SOURCE_RESOURCES task.

coriolis/conductor/rpc/client.py, coriolis/conductor/rpc/server.py, coriolis/replica_cron/rpc/client.py, coriolis/rpc.py, coriolis/scheduler/rpc/client.py, coriolis/worker/rpc/client.py
Due to some underlying issue related to the usage/implementation of the
oslo_messaging.RPCClient, cross-components connecions are not getting
properly closed, leading to numerous hanging connections and eventual
saturation of all ports available on the Rabbit host.
This PR adds a base class in the `coriolis.rpc` module which facilitates
automatic cleanup for all RPC calls.
=> Ensure RPC call connection cleanup across all components.

coriolis/cmd/api.py, coriolis/cmd/conductor.py, coriolis/cmd/worker.py, coriolis/service.py, coriolis/worker/rpc/server.py
This patch adds a new command line argument ('--worker-process-count')
to the components which need it (API, Conductor, and Worker) to allow
for CLI-based control on the number of worker processes spawned.
Note that this will NOT stop the components from forking if they are
programmed to do so, but merely stops oslo_service from forking the main
process at initial startup.
=> Add --worker-process-count argument to relevant components.

coriolis/minion_manager/rpc/server.py
Ensure that the minion manager does not bother trying to reuse
destination transfer minions for Replica deployments or if no transfer
minions were requested to begin with.
=> Prevent minion reuse error for Replica deployments.

coriolis/conductor/rpc/client.py
This prevents possible desync problems when it comes to operations like
confirming task running or process setting.
=> Make task-related worker-conductor interactions synchronous.

coriolis/db/api.py, coriolis/db/sqlalchemy/migrate_repo/versions/009_Migrate_info_to_blob.py, coriolis/db/sqlalchemy/types.py
Changes are:
- switching base_transfer_action.info base sqlalchemy type from
to `LongBinary` since plain `Binary` no longer exists.
This should not affect existing deployments since the underlying
SQL type is still `longblob`
- use `filter` instead of `filter_by` for `max` queries.
=> Update DB layer for SQLAlchemy 1.4.

requirements.txt
The latest versions oslo_messaging and kombu cause exterme RAM usage in
the API service. Coriolis can be ruled out as the cause as individual
testing showed kombu to the single biggest factor.
This PR mitigates this by pinning both to their prior major releases.
=> Add version requirement for oslo_messaging and kombu.

coriolis/conductor/rpc/server.py
Due to a logical lapsus, on-error tasks which only depended on other
on-error tasks were unscheduled by the conductor.
(most notable being the RESTORE_REPLICA_DISKS_SNAPSHOTS task)
=> Ensure on-error tasks with exclusively on-error parents are started.

coriolis/osmorphing/osmount/base.py
In some cases, upon volume group activation, its logical volumes' partitions don't get recognized on the minion, only after a metadata refresh
=> Refresh volume group metadata upon activation

setup.cfg
`setuptools` will deprecate usage of dashes in the metadata fields from
setup.cfg.
=> Futureproof setup.cfg by replacing dashes with underscores.

coriolis/conductor/rpc/server.py
When a Replica schedule gets deleted, the Keystone trust that is supposed to
be used for the replica execution is also deleted, which automatically means
the execution will fail.
=> Forbid Replica schedule deletion while the replica is not in a finalized state

coriolis/providers/provider_utils.py
Any storage mapping update automatically fails, without checking whether the `volumes_info` actually exists or not. `volumes_info` argument wasn't used up to this point, this may be the main reason we kept passing it.
=> Check replica volumes exist before raising storage mapping update error

coriolis/api/v1/migrations.py, coriolis/api/v1/replicas.py, coriolis/api/v1/views/migration_view.py, coriolis/api/v1/views/replica_tasks_execution_view.py, coriolis/api/v1/views/replica_view.py, coriolis/conductor/rpc/client.py, coriolis/conductor/rpc/server.py, coriolis/db/api.py, coriolis/db/sqlalchemy/models.py, coriolis/migrations/api.py, coriolis/replicas/api.py
-  Adds `include_task_info` option to all DB API action fetching methods that
will control the loading of `info` column for a `BaseTransferAction`.
Also adds `to_dict` option that turns the model objects into dictionaries
for GET requests. This is necessary because serialization of model objects
with deferred columns is not possible without an active DB session.
-  Expose `include_task_info` parameters to `include_tasks_info_in_api` config options
=> Add `include_task_info` to action DB fetching operations

coriolis/api/v1/views/migration_view.py
`last_execution_status` key from DB should be used instead.
=> Remove migration `status` from API response view

coriolis/utils.py
If a stdout or stderr stirng decoding may fail, it will raise an exception and
may wrongfully interrupt a running task. This patch will ignore string
decoding errors and, if decoding errors do occur, output the encoded
bytestring.
=> Prevent SSH command output decoding from raising exceptions

coriolis/osmorphing/ubuntu.py
Adds Ubuntu release 22.04 value as supported Ubuntu OS.
=> Add Ubuntu 22.04 release to `BaseUbuntuMorphingTools`

coriolis/osmorphing/osmount/windows.py, coriolis/providers/backup_writers.py
These patches include the following:
1. Fixes backup writer offset logging, by logging the right offset when the transfer finishes, so no duplicate offsets will show up in the logs.
2. Adds verbose logging to HTTP writer
3. Removes `Exception ocurred while servicing disk` progress update. Only the logged warning message remains.
=> Logging message improvements

coriolis/providers/replicator.py, coriolis/tasks/minion_pool_tasks.py
Add `127.0.0.1` address to replicator certificate hosts
This patch aims to fixing connection to the replicator service using SSH
tunneling. SSL handshake fails if the certificates don't include the
`127.0.0.1` extra host.
Add `minion_connection_info` to minion volume attachment/detachment methods
Adding the minion connection info to these methods will make it possible for
the destination providers to setup the replicator service and attach the disks
using it, to better detect attached device paths.
=> Minion machine disk attachment update

requirements.txt
Fixes requirement pip installation on newer Operating Systems that deprecated OpenSSL 1.1.
Limits `sqlalchemy` version, since `sqlalchemy-migrate` has been also deprecated.
=> Fix requirements for running workflow tests

coriolis/exception.py
Should be raised when there’s an invalid VM state.
=> Add `InvalidInstanceState` exception type

coriolis/osmorphing/oracle.py, coriolis/osmorphing/redhat.py, coriolis/osmorphing/suse.py
When regenerating initrds, Coriolis would only regenerate for official kernel versions and RPM packages. This patch makes use of `dracut --regenerate-all` command to make sure that all initrds are regenerated in the OS Morphing process.
=> Regenerate all initrds using dracut command

requirements.txt
`oslo.db` has removed `sqlalchemy.migrate` module after sqlalchemy-migration has been deprecated (https://github.com/cloudbase/coriolis/pull/248). This patch pins down `oslo.db` to the last version this module still exists, until proper fix (switching to `alembic` DB migrations).
=> Fix deprecation of `sqlalchemy migrate` in `oslo.db`

coriolis/osmorphing/centos.py, coriolis/osmorphing/oracle.py, coriolis/osmorphing/osdetect/centos.py, coriolis/osmorphing/osdetect/manager.py, coriolis/osmorphing/osdetect/rocky.py, coriolis/osmorphing/rocky.py
This PR will add core support for OSMorphing Tools that support the following Linux distributions: 
- CentOS Stream (any version)
- Oracle Linux 9
- Rocky Linux (>=8)
=> Upgrade RHEL-based OSMorphing Tools

coriolis/providers/backup_writers.py, coriolis/utils.py
**- Correct SELinux label on created systemd services**
This patch makes sure that services created by Coriolis (like coriolis-writer)
can run on a SELinux enabled worker machine, by correcting the service file's
label, so systemctl can read it.
**- Remove another lvm udev rule**
On even newer systems, udev rules containing `pvscan` commands would interfere
with normal migrations with multiple replication processes. This patch
removes such rules before starting the HTTPS backup writer service.
=> HTTPS backup writer transfer fixes

coriolis/osmorphing/osmount/base.py, coriolis/utils.py
**Fix hanging SSH command on Ubuntu worker**
When executing `sudo /sbin/xxxx` on a Ubuntu worker machine, sudo will always
ask for a password, even though the user is set as passwordless, and even if
the binary does not exist. This patch removes any trace of `/sbin/xxxx`
sudo commands.
**Rename duplicate VG names**
Duplicate VG names interfere with the OSMorphing process. This patch makes
sure there are no duplicate volume group names before activating them.
=> More worker-related fixes

coriolis/providers/replicator.py
The purpose of this PR is to provide a more user-friendly error messages when SSH exceptions are encountered. For example, instead of printing a generic message like "Authentication failed" it's better to provide more context by indicating that the error is related to the SSH client. Also, an optional timeout was added to wait for the SSH banner to be presented.
=> added a try-block to catch the SSH error

coriolis/cmd/__init__.py, coriolis/conf.py
This patch will register common options before starting services, but instead of just importing the `conf` module and let the registering occur implicitly, it calls `conf.init_common_opts` explicitly.
=> Fix common option register

coriolis/db/api.py
Whenever a GET call to a non-existent object is requested, the server would not return a proper `404` code response. Instead, it returned a `500`, because `.to_dict()` was called upon the not found object directly (which should be `None`). This patch makes sure that `.to_dict()` is only called upon existing DB models, and as a result, it will return a `404` response on not found objects.
=> Fix DB fetching on not found entries

coriolis/api/middleware/auth.py, coriolis/tests/api/middleware/test_auth.py
This PR adds unit tests for Coriolis/api/middleware/auth.py
=> Add unit tests for Coriolis api

coriolis/tests/test_context.py
This PR adds unit tests for the `context.py` module.
=> Add unit tests for the `context.py` module

coriolis/tests/test_data_transfer.py
This PR adds unit tests for the `data_tranfer.py` module.
=> Add unit testing for the `data_tranfer.py` module

coriolis/tests/worker/rpc/data/get_custom_ld_path.yml, coriolis/tests/worker/rpc/test_server.py, coriolis/worker/rpc/server.py
This patch will complete the test coverage for `worker.rpc.server` module
=> Complete worker RPC server tests

coriolis/tests/worker/rpc/test_server.py
This patch fixes the invalid calls to `assertLogs`. This assertion method was supposed to be used as a context manager, therefore just calling it would not in fact assert to anything.
=> Fix invalid `assertLogs` usages

coriolis/keystone.py, coriolis/tests/test_exception.py, coriolis/tests/test_i18n.py, coriolis/tests/test_keystone.py, coriolis/tests/test_policy.py
This PR adds more unit testing for the following modules:
* `exception.py`
* `i18n.py`
* `keystone.py`
* `policy.py`
=> Add more unit tests for `coriolis` main modules

coriolis/osmorphing/osmount/windows.py
Attempt to lower RTO when migrating Windows VMs by speeding up OSMount process. This speed-up is based on ditching diskpart scripts (which would increase time overhead by writing every script to a `.txt` file and execute it after), and instead directly send equivalent PowerShell commands. This patch also deprecates the migration of Windows dynamic disks.
=> Improve Windows OSMount process speed

coriolis/osmorphing/base.py, coriolis/osmorphing/centos.py, coriolis/osmorphing/debian.py, coriolis/osmorphing/openwrt.py, coriolis/osmorphing/redhat.py, coriolis/osmorphing/rocky.py, coriolis/osmorphing/suse.py
This patch refactors the setup of GRUB2 console settings into `BaseLinuxOSMorphingTools`, so more providers could use it directly.
=> Refactor GRUB2 console settings setup for migrated Linux machines

coriolis/osmorphing/osmount/windows.py
This patch will make sure that every disk is dismounted one by one from the Windows OSMorphing worker, in order to account for workers that have temporary disks attached by default (currently common on Azure platform). This will also prevent the migration task failure in case a disk cannot be set to offline.
=> Attempt dismounting Windows disks one by one

coriolis/taskflow/base.py, coriolis/tests/taskflow/test_base.py, coriolis/tests/taskflow/test_runner.py, coriolis/tests/taskflow/test_utils.py
This PR adds unit tests for the following modules:
* `taskflow/runner.py`
* `taskflow/utils.py`
* `taskflow/base.py`
=> Add unit tests for `coriolis/taskflow` modules 

coriolis/tests/cmd/test_api.py, coriolis/tests/cmd/test_conductor.py, coriolis/tests/cmd/test_db_sync.py, coriolis/tests/cmd/test_minion_manager.py, coriolis/tests/cmd/test_replica_cron.py, coriolis/tests/cmd/test_scheduler.py, coriolis/tests/cmd/test_worker.py
This PR add unit tests for 'coriolis.cmd.*' modules
=> Add unit tests for `coriolis.cmd.*` modules

coriolis/tests/scheduler/filters/test_base.py, coriolis/tests/scheduler/filters/test_trivial_filters.py, coriolis/tests/scheduler/rpc/test_client.py, coriolis/tests/scheduler/rpc/test_server.py, coriolis/tests/scheduler/test_scheduler_utils.py, coriolis/tests/services/test_api.py
This PR adds unit tests for the following modules:
* `services/api.py`
* `scheduler/scheduler_utils.py`
* `scheduler/rpc/client.py`
* `scheduler/rpc/server.py`
* `scheduler/filters/base.py`
* `scheduler/filters/trivial_filters.py`
=> Add unit tests for `coriolis/scheduler` and `coriolis/services` modules

coriolis/osmorphing/osmount/redhat.py, coriolis/osmorphing/osmount/ubuntu.py, coriolis/providers/replicator.py
This PR includes some fixes required on modern OS images:
- Fix SSH reload on OSMorphing worker
Fixes SSH daemon restart on newer versions of Linux OSMorphing workers by using
`systemctl`, if available. Formerly, `service` command was used by default,
which is no longer available on newer images.
- Set binary context on replicator binary
Sets valid SELinux file context for the copied `replicator` service binary, in
order for the service to start on a SELinux-enabled worker machine.
=> Various OS upgrade fixes

coriolis/osmorphing/osmount/windows.py
This patch makes sure all mounted partitions get a drive letter assigned, especially useful for VirtIO disks which on some Windows guests are implemented as removable drives, which get no boot drive letter by default.
=> Set default drive letter to all Windows partitions

coriolis/tests/conductor/rpc/test_utils.py
This PR adds unit tests for `coriolis.conductor.rpc.utils` module
=> Add tests for `coriolis.conductor.rpc.utils` module

coriolis/osmorphing/osmount/ubuntu.py
Add wait/retry to the pre-setup stage of the Ubuntu OSMorphing minions for installing packages required by the OSMount process.
=> [OSMount] Add waits/retry during Ubuntu minion prep stage.

coriolis/conductor/rpc/server.py, coriolis/tests/conductor/rpc/data/cancel_migration_config.yml, coriolis/tests/conductor/rpc/data/confirm_task_cancellation.yml, coriolis/tests/conductor/rpc/data/update_replica_config.yml, coriolis/tests/conductor/rpc/test_client.py, coriolis/tests/conductor/rpc/test_server.py
This PR adds unit tests for `coriolis.conductor.*` modules
=> Add unit tests for `coriolis.conductor.*` modules

coriolis/tests/endpoint_resources/test_api.py
This PR adds unit tests for `coriolis.endpoint_resources.api` module
=> Add tests for `coriolis.endpoint_resources.api` module

coriolis/tests/endpoints/test_api.py
This PR adds unit tests for `coriolis.endpoints.api` module
=> Add tests for `coriolis.endpoints.api` module

coriolis/tests/cron/test_cron.py
This PR adds unit tests for `coriolis.cron` module
=> Add tests for `coriolis.cron` module

.github/workflows/unit-tests.yml, tox.ini
Enables `cover` tox env when creating PRs.
=> Enable unit test coverage checking

coriolis/tests/osmorphing/test_amazon.py, coriolis/tests/osmorphing/test_base.py, coriolis/tests/osmorphing/test_centos.py, coriolis/tests/osmorphing/test_coreos.py, coriolis/tests/osmorphing/test_debian.py, coriolis/tests/osmorphing/test_manager.py, coriolis/tests/osmorphing/test_openwrt.py, coriolis/tests/osmorphing/test_oracle.py, coriolis/tests/osmorphing/test_redhat.py, coriolis/tests/osmorphing/test_rocky.py, coriolis/tests/osmorphing/test_suse.py, coriolis/tests/osmorphing/test_ubuntu.py, coriolis/tests/osmorphing/test_windows.py
This PR adds unit testing for the following modules:
* `osmorphing/amazon.py`
* `osmorphing/base.py`
* `osmorphing/centos.py`
* `osmorphing/coreos.py`
* `osmorphing/debian.py`
* `osmorphing/manager.py`
* `osmorphing/openwrt.py`
* `osmorphing/oracle.py`
* `osmorphing/redhat.py`
* `osmorphing/rocky.py`
* `osmorphing/suse.py`
* `osmorphing/ubuntu.py`
* `osmorphing/windows.py`
=> Add unit tests for `osmorphing` module

coriolis/diagnostics/api.py, coriolis/tests/diagnostics/test_api.py
This PR adds unit tests for `coriolis.diagnostics.api` module
=> Add tests for `coriolis.diagnostics.api` module

tox.ini
This PR fixes inaccurate coverage rate by omitting `coriolis/tests` from cover
=> Cover: Omit unit tests directory

coriolis/tests/minion_pools/test_api.py
This PR add unit testing for the `minion_pools/api.py` module.
=> Add unit tests for `minion_pools/api.py` module

coriolis/tests/migrations/test_api.py
This PR adds test cases for `coriolis/migrations/api.py` module
=> Add unit tests for `migrations/api.py` module

coriolis/tests/licensing/test_client.py
This PR add unit tests for `coriolis/licensing/client.py` module.
=> Add unit testing for `licensing/client.py` module

coriolis/tests/osmorphing/osmount/test_base.py, coriolis/tests/osmorphing/osmount/test_factory.py, coriolis/tests/osmorphing/osmount/test_redhat.py, coriolis/tests/osmorphing/osmount/test_ubuntu.py, coriolis/tests/osmorphing/osmount/test_windows.py
This PR adds unit testing for the following modules:
* `osmorphing.osmount.base.py`
* `osmorphing.osmount.factory.py`
* `osmorphing.osmount.redhat.py`
* `osmorphing.osmount.ubuntu.py`
* `osmorphing.osmount.windows.py`
=> Add unit tests for `osmorphing.osmount*`

coriolis/tests/__init__.py
When mocking something, there's the possibility to reference a property that does not exist, or call a method with invalid arguments, but the unit tests to keep passing, resulting in false positives.
We've seen this issue several times in OpenStack, and we have created and started using a mock patch fixture (can be seen in OpenStack Nova's ``test.py``) which enables autospec by default.
This guarantees 2 things: that the thing we're patching exists, and if it's callable, that the calls respect the callable's signature (e.g.: no unknown arguments can be used).
=> tests: Adds mock patch autospec fixture

coriolis/osmorphing/osmount/base.py, coriolis/tests/osmorphing/osmount/test_base.py
The Coriolis OSMount code would internally keep a mapping between names of VGs it should activate and their PVs, which could potentially lead to VGs with multiple PVs to be referneced both by their original name, as well as a new one Coriolis generates to avoid naming conflicts in /dev/$VG_NAME/$LVM_NAME.
=> OSMount: fix internal VG name referencing conflict.

coriolis/osmorphing/osmount/base.py
This commit aims to fix an issue where multiple swap partitions that have the same 'none' or 'swap' as mountpoint. In order to achieve this, the linux OSMount tools will skip any mountpoint that is not a valid directory.
=> Skip fstab mountpoints that are not valid directory paths

coriolis/osmorphing/osmount/redhat.py
System Device filters is a feature enabled by default on RHEL9-based images, which limits the LVM detection on a particular set of system devices, provided in the `system.devices` file. This is bad for the OSMount process, since it will fail to detect LVM volumes on the migrated partitions. Removing the `system.devices` file from the minion machine disables this feature and fixes the issue.
=> Remove LVM system device filters for RedHat OSMount Tools

coriolis/licensing/client.py, coriolis/tests/licensing/test_client.py
This PR fixes error log in licensing client when deleting reservation.
=> Fix licensing client error logging

coriolis/keystone.py, coriolis/service.py
Thic change adds the ability to specify a CA cert file to use when validating requests to the rest of the openstack projects and adds a function that returns a WSGI app which can be used with `mod_wsgi` and similar.
=> Handle wsgi and add CA file option

coriolis/osmorphing/osmount/base.py, coriolis/osmorphing/osmount/redhat.py, coriolis/osmorphing/osmount/ubuntu.py, coriolis/tests/osmorphing/osmount/test_base.py
On newer Ubuntu (starting with 24.04) Server images, `sshd` service name has been changed to `ssh`. This patch handles this rename and refactors it into the base OSMount class, in order for it to be picked up for all Linux OSMount minions.
=> Refactor and fix SSH service restart on OSMount worker SSH env configuration

coriolis/keystone.py
Allows the connection info to set/unset the SSL verification by its `allow_untrusted` option.
=> Fix Keystone session creation connection options

coriolis/osmorphing/redhat.py, coriolis/tests/osmorphing/test_redhat.py
This PR add check for installed package and checks that grubby is installed before trying to install it.
=> [OSMorphing] Add check for installed package

coriolis/minion_manager/rpc/tasks.py, coriolis/tests/minion_manager/rpc/test_client.py, coriolis/tests/minion_manager/rpc/test_tasks.py
This PR adds test cases for the following module:
- `minion_manager.rpc.tasks.py`
- `minion_manager.rpc.client.py`
=> Add `minion_manager.rpc.client.py/tasks.py` unit tests

coriolis/osmorphing/base.py, coriolis/osmorphing/coreos.py, coriolis/osmorphing/debian.py, coriolis/osmorphing/manager.py, coriolis/osmorphing/openwrt.py, coriolis/osmorphing/redhat.py, coriolis/osmorphing/suse.py, coriolis/osmorphing/windows.py, coriolis/tests/osmorphing/test_base.py, coriolis/tests/osmorphing/test_debian.py, coriolis/tests/osmorphing/test_manager.py, coriolis/tests/osmorphing/test_openwrt.py, coriolis/tests/osmorphing/test_redhat.py, coriolis/tests/osmorphing/test_suse.py
This PR adds check_installed_package for Redhat, Debian and SUSE.
=> [OSMorphing] Check installed packages before installing packages

coriolis/osmorphing/osmount/base.py, coriolis/tests/osmorphing/osmount/test_base.py
This PR implements the following updates:
* Added a check to verify the existence of the `device` before attempting to `mount` it;
* Included a `unit test` for this scenario;
=> `OSMount` - Fix handling of non-existent devices

coriolis/db/api.py, coriolis/minion_manager/rpc/server.py
**Only fetch minion pool events and progress updates when actually needed**
This patch will make sure that getting minion pool events and progress updates
will only occur when actually printing them out to the UI or CLI, and
excluding them otherwise.
**Fix cartesian product on minion pool fetching**
When multiple `joinedload`s were queried, it resulted in a cartesian product
list of rows. Switching to `selectinload`, while performing multiple queries
to the DB server, will make sure that the minimum amount of rows get returned
from the DB. This fixes hangups when fetching progress updates and events of
long-running minion pools.
=> Minion pooling optimizations

coriolis/tests/db/sqlalchemy/test_api.py, coriolis/tests/db/sqlalchemy/test_migration.py, coriolis/tests/db/sqlalchemy/test_models.py, coriolis/tests/db/sqlalchemy/test_types.py
This PR add unit tests for `coriolis.db.sqlalchemy.*` modules
=> Add unit tests for `coriolis.db.sqlalchemy.*` modules

coriolis/worker/rpc/server.py
This patch removes the sleep added to avoid high CPU usage caused by an eventual infinite loop. It's not the case of infinite loops on logging queue, therefore it is safe to remove it.
=> Fix logging delay for worker task processes

coriolis/utils.py
When downloading diagnostics logs, each service diagnostic will return a `release_tag`, which will reference the service's stable release version, or `latest` otherwise.
=> Adds ability to fetch release tag when requesting diagnostics

coriolis/osmorphing/redhat.py, coriolis/tests/osmorphing/test_redhat.py
- Fixes the 'Permission denied' error based on the read permission of the `/etc/yum.repos.d/`
- Sends a warning in case of repository not being parsed due to an error
- Updates the redhat tests to match the call of the new method
=> Fix issue 'Permission denied' error due to repo permissions on redhat linux

coriolis/schemas/vm_export_info_schema.json, coriolis/tasks/replica_tasks.py, coriolis/tests/tasks/data/test_hostname_update.yml, coriolis/tests/tasks/test_replica_tasks.py
Adds `hostname` property to the instance export information, used in order to attempt hostname preservation
=> Add `hostname` to export_info

requirements.txt
Since we're currently still using Openstack Antelope containers oslo has just had a few repos tagged May 16th which broke worker rpc registration. We'll have to pin the requirements until the rest of the codebase catches up.
=> Pin oslo.context and oslo.config

coriolis/conductor/rpc/server.py, coriolis/deployer_manager/rpc/server.py
This PR includes the following:
- **Fix deployer manager failing deployments when awaiting for minions**
If the deployer transfer starts with a minion pool, the deployer manager
would've considered the `AWAITING_MINION_ALLOCATIONS` status as an invalid
one, and thus error out the automatically launched deployment. This patch
adds this minion status as an active and valid one, and properly waits for
the deployer to finish with minion refreshment and the transfer execution as
well.
- **Wait for deployer threads**
This patch makes sure that all deployer manager threads finish before launching
new ones. By immediately launching new ones, there was a risk where after the
deployer completes, the threads would simultaneously create deployment
executions, which breaks deployments and transfers, …
=> Deployer manager safety fixes and improvements

coriolis/api/v1/deployments.py, coriolis/api/v1/transfers.py, coriolis/api/v1/utils.py, coriolis/conductor/rpc/server.py, coriolis/tests/api/v1/test_transfers.py, coriolis/tests/api/v1/test_utils.py, coriolis/tests/conductor/rpc/test_server.py
This PR addresses an issue where instance user scripts added during deployment were not actually processed, which caused them to be unavailable during OS morphing.
To fix this, the _normalize_user_scripts logic was refactored and moved from coriolis.api.v1.utils to the ConductorServerEndpoint class, where it is now used only during the deployment stage of the transfer.
Related unit tests have also been refactored and moved into test_server.py.
=> instance user_scripts fix on deployments

coriolis/conductor/rpc/server.py, coriolis/tests/conductor/rpc/test_server.py
* The `get_transfers()` RPC method was passing `include_tasks_executions` as a positional argument instead of a keyword argument to the database API, causing incorrect parameter mapping and empty transfer lists.
=> Fix missing `kwarg` in `get_transfers` RPC method
