cloudbase/coriolis

coriolis/osmorphing/osmount/base.py

For some reason, we were ignoring the first device in the list because of the assumption that it belonged to the worker VM. This change looks in /proc/mounts for already mounted devices. This way there is no way to confuse the worker VM root device for the root device of the instance we are migrating

Fix os_mount()

---

coriolis/osmorphing/osmount/windows.py

After changing the base class, forgot to also change the Windows mount_os() return values. Sory about that!

Fix Windows mount_os()

---

coriolis/migrations/manager.py

Do as the comment says.
This reduces the number of round trips and makes transfers considerably faster.

Fix chunk size

---

coriolis/osmorphing/windows.py

In cases where System.IO.Compression.ZipFile is available on the
windows minion, if the destination folder exists, it will cause
an error.
Where this component is not available, if the target folder exists
and there are conflicting files inside it with what's inside the
archive, it will error out.
In both cases, ensuring that the destination folder does not exist
will fix the issue.
If the destination folder is the root folder or is within the
%WINDOWS% folder, we do not remove it.

Fix _expand_archive()

---

coriolis/utils.py

This change allows the creation of system start-up scripts for upstart and systemd on remote temporary workers.

Add system startup creation functions

---

coriolis/api/v1/endpoint_instances.py
coriolis/conductor/rpc/client.py
coriolis/conductor/rpc/server.py
coriolis/endpoint_instances/api.py
coriolis/providers/base.py
coriolis/worker/rpc/client.py
coriolis/worker/rpc/server.py

Add 'env' option during get_instance(s) API calls

---

coriolis/providers/backup_writers.py

This change disables lvm2-lvmetad before starting the disk sync.

Disable lvm2-lvmetad before disk sync

---

coriolis/providers/replicator.py

Create a group for the Replicator user on the export minion VM.
Additionally, add the SSH user to the group in order to be able to the replicator's certificates.

Create group for Replicator user.

---

coriolis/osmorphing/base.py
coriolis/osmorphing/debian.py
coriolis/utils.py

This change calls sync in _write_file_sudo() to ensure that the files written to disk actually make it on the disk.

Call sync in _write_file_sudo() and PEP8

---

coriolis/osmorphing/osmount/base.py

Find and mount root device with all virtual filesystems first, then the boot device if any, then any secondary partitions present in target machine fstab.

Fix mount os

---

coriolis/db/sqlalchemy/types.py

When using the replicator, we need to save the previous state of
the disk in the DB. Depending on disk size and chunk size, that
can add up to a lot of data. This change compresses the json using
zlib to ease storage needs on the DB.

Compress Bson fields

---

coriolis/cache.py
requirements.txt

Adds a caching module that providers may leverage.

Add caching module

---

coriolis/providers/backup_writers.py
coriolis/resources/write_data.c

* check for out of bounds write
* check if write_data died before attempting to send a chunk. This will return a proper error code, and not mask it with ```Socket closed``` messages.

Handle writer error

---

coriolis/osmorphing/osmount/base.py

When unmounting a directory, 'target is busy' error mostly appears if whether:
- There are mountpoints inside the target directory;
- Running processes use the target directory, preventing it from unmonting.
This patch covers the cases mentioned above when dismounting migrated OS.

Fix 'target is busy' when dismounting OS from worker instance.

---

coriolis/providers/replicator.py

For platforms where the disk attachment order is unpredictable, the
plugins can choose to call a method on the Replicator object which
automatically runs and detects the new disk attachment, and returns the
new volumes_info for it.

Add disk attachment detection functionality to Replicator.

---

coriolis/api/v1/diagnostics.py
coriolis/api/v1/router.py
coriolis/api/v1/views/diagnostic_view.py
coriolis/conductor/rpc/client.py
coriolis/conductor/rpc/server.py
coriolis/diagnostics/api.py
coriolis/policies/diagnostics.py
coriolis/policy.py
coriolis/replica_cron/rpc/client.py
coriolis/replica_cron/rpc/server.py
coriolis/utils.py
coriolis/worker/rpc/client.py
coriolis/worker/rpc/server.py

Fetch basic diagnostics from coriolis components.

Add diagnostics

---

coriolis/osmorphing/base.py
coriolis/osmorphing/debian.py
coriolis/osmorphing/oracle.py
coriolis/osmorphing/osmount/base.py
coriolis/osmorphing/redhat.py
coriolis/osmorphing/suse.py
coriolis/providers/backup_writers.py
coriolis/utils.py

There are situations where sshd_config can be set to require a
tty when sending sudo commands(Default requiretty). This patch
should always set Coriolis to send sudo commands using pty.

Send sudo SSH commands through a pseudo-terminal.

---

coriolis/api/v1/migrations.py
coriolis/conductor/rpc/client.py
coriolis/conductor/rpc/server.py
coriolis/migrations/api.py
coriolis/osmorphing/base.py
coriolis/osmorphing/manager.py
coriolis/osmorphing/windows.py
coriolis/tasks/osmorphing_tasks.py
coriolis/utils.py

These user defined scripts will run before any OS morphing operation
will take place.

Add user defined scripts for OS morphing

---

coriolis/conductor/rpc/server.py

Due to the current Replica state model, the Replica/Migrations
source/target resource deletion/creation tasks can potentially override
each-other's state.
This patch makes the tasks run in sequence to ensure this does not
happen.

Execute Replica/Migration source/dest resource tasks in sequence.

---

coriolis/providers/base.py
coriolis/tasks/replica_tasks.py

Updated base interfaces and necessary core-side refactoring.

Separate replica source resource deployment

---

coriolis/osmorphing/suse.py

* Add openSUSE enable repo baed on NAME and VERSION_ID in /etc/os-release
* Add enable SLES module based on SUSEConnect providing the correct module for each SLES version

Add sles module enable; add suse cloud tools repo

---

coriolis/exception.py
coriolis/osmorphing/base.py
coriolis/osmorphing/centos.py
coriolis/osmorphing/coreos.py
coriolis/osmorphing/debian.py
coriolis/osmorphing/manager.py
coriolis/osmorphing/openwrt.py
coriolis/osmorphing/oracle.py
coriolis/osmorphing/osdetect/base.py
coriolis/osmorphing/osdetect/centos.py
coriolis/osmorphing/osdetect/coreos.py
coriolis/osmorphing/osdetect/debian.py
coriolis/osmorphing/osdetect/manager.py
coriolis/osmorphing/osdetect/openwrt.py
coriolis/osmorphing/osdetect/oracle.py
coriolis/osmorphing/osdetect/redhat.py
coriolis/osmorphing/osdetect/suse.py
coriolis/osmorphing/osdetect/ubuntu.py
coriolis/osmorphing/osdetect/windows.py
coriolis/osmorphing/osmount/base.py
coriolis/osmorphing/redhat.py
coriolis/osmorphing/suse.py
coriolis/osmorphing/ubuntu.py
coriolis/osmorphing/windows.py
coriolis/providers/base.py
coriolis/schemas.py
coriolis/schemas/detected_os_morphing_info_schema.json
coriolis/utils.py

Early WiP, please ignore for the time being.

[WiP] Overhaul detection and tool selection during OSMorphing.

---

coriolis/conductor/rpc/server.py

Account for possibility of worker services failing/refusing/missing cancellation requests while advancing Execution states.

Improve reliability of task cancellation.

---

coriolis/conductor/rpc/client.py
coriolis/conductor/rpc/server.py
coriolis/db/api.py
coriolis/db/sqlalchemy/models.py
coriolis/events.py
coriolis/worker/rpc/server.py

- Mainly fixed by sorting progress updates by current_step
- current_step incrementation now occurs in db/api.py
- Added separate methods for adding and updating progress updates

Fix clobbering of Task progress updates

---

coriolis/api/v1/replicas.py
coriolis/api/v1/utils.py
coriolis/conductor/rpc/server.py

Necessary when upgrading from older releases

Add default value to user_scripts column

---

coriolis/api/v1/migrations.py
coriolis/api/v1/replicas.py
coriolis/events.py
coriolis/providers/backup_writers.py

This PR fixes excessive progress updates sent by percentage steps, and deprecates the ```detail()``` function in both migrations and replica views.

Various performance fixes

---

coriolis/osmorphing/oracle.py
coriolis/osmorphing/redhat.py

This PR includes the following fixes:
1. Filter files ending in '.repo' when searching for yum repos
yum internally only works with repos that reside in files ending
with '.repo'. This patch should make sure that Coriolis only looks
for repos inside files with filenames ending in '.repo'.
2. Manually configure yum repos instead of using yum-config-manager
`yum-config-manager --add-repo` automatically adds and enables the
repos from a URL. This being against our ideal OSMorphing
functionality, this patch will manually download the repo file
and should also make sure to disable all downloaded repos.

Fix yum repos bugs

---

coriolis/providers/backup_writers.py

Some newer OS releases have udev rules that create lvm2-pvscan services for each disk with detected lvm partitions (usually after a replication transfer is complete), making normal migrations using multiple replications impossible to complete, as it interferes with the second replication process by not having the disk file available. This patch deletes the udev rules upon backup writer setup.

Disable lvm-metad udev rules when setting up backup writer

---

.github/workflows/unit-tests.yml
coriolis/tests/conductor/rpc/test_server.py

Unit tests are run on pull requests by using this action.
Also includes a small fix for a failing tes

Add GitHub Workflow action for unit test running

---

coriolis/providers/backup_writers.py

Adds equivalent command of `iptables` for `nft` when injecting ingress rule for backup writer's TCP port.

Add `nftables` command when injecting backup writer firewall rule

---

coriolis/providers/backup_writers.py

This patch fixes the coriolis-writer service not starting on SELinux enabled machines by changing the type context of the binary to `bin_t`.
It also adds additional firewall writer setup command for firewalld service.

Fix backup writer setup on SELinux-enabled worker machines.

---

coriolis/wsman.py

Adds a readable error message to `WSManConnection.download_file` method, instead of dumping the whole PS stderr to frontend.

Adds error message on WSMan File Download failure.

---

coriolis/tasks/replica_tasks.py

The `volumes_info` errors present in replica tasks are now redacted. As a result, the `chunks` field is no longer fully displayed.

Redact unnecessary `volumes_info` keys in errors

---

coriolis/tests/conductor/rpc/data/advance_execution_state.yml
coriolis/tests/conductor/rpc/data/cancel_tasks_execution_config.yml
coriolis/tests/conductor/rpc/data/get_execution_status_config.yml
coriolis/tests/conductor/rpc/data/set_task_error_config.yml
coriolis/tests/conductor/rpc/data/task_completed_config.yml
coriolis/tests/conductor/rpc/test_server.py

Based on https://github.com/cloudbase/coriolis/pull/250.
Please merge #250 first.

Batch of unit tests for `ConductorServerEndpoint`

---

coriolis/tests/test_cache.py

This PR add unit tests for the `cache.py` module.

Implement unit testing for the `cache` module

---

coriolis/tests/test_cache.py

This PR fixes cache unit test pep8 error.

Fix pep8 cache unit test

---

coriolis/tests/test_events.py

This PR adds unit testing for the `events.py` module.

Add unit tests for the `events.py` module

---

coriolis/osmorphing/amazon.py
coriolis/osmorphing/osdetect/amazon.py
coriolis/osmorphing/osdetect/manager.py

This patch adds Amazon Linux OS detection and core OSMorphing tools

Add OSMorphing Support for Amazon Linux

---

coriolis/providers/replicator.py
coriolis/tests/providers/test_api.py
coriolis/tests/providers/test_backup_writers.py
coriolis/tests/providers/test_factory.py
coriolis/tests/providers/test_provider_utils.py
coriolis/tests/providers/test_replicator.py
coriolis/tests/regions/test_api.py
coriolis/tests/replica_cron/rpc/test_client.py
coriolis/tests/replica_cron/rpc/test_server.py
coriolis/tests/replica_cron/test_api.py
coriolis/tests/replica_tasks_executions/test_api.py
coriolis/tests/replicas/test_api.py

This PR adds more unit tests for the following modules:
* `replicas/api.py`
* `replica_tasks_executions/api.py`
* `replica_cron/api.py`
* `replica_cron/rpc/client.py`
* `replica_cron/rpc/server.py`
* `regions/api.py`
* `providers/api.py`
* `providers/factory.py`
* `providers/provider_utils.py`
* `providers/replicator.py`
* `providers/backup_writers.py`

Add more unit testing

---

coriolis/osmorphing/base.py
coriolis/osmorphing/coreos.py
coriolis/osmorphing/debian.py
coriolis/osmorphing/openwrt.py
coriolis/osmorphing/redhat.py
coriolis/osmorphing/suse.py
coriolis/osmorphing/windows.py

This PR changes `installed_packages` attribute to be defined in `get_installed_packages` implementation and adds missing definition.

[OSMorphing] Fix undefined attribute installed_packages

---

coriolis/osmorphing/base.py
coriolis/osmorphing/debian.py
coriolis/osmorphing/netpreserver/base.py
coriolis/osmorphing/netpreserver/factory.py
coriolis/osmorphing/netpreserver/ifcfg.py
coriolis/osmorphing/netpreserver/interfaces.py
coriolis/osmorphing/netpreserver/netplan.py
coriolis/osmorphing/netpreserver/nmconnection.py
coriolis/osmorphing/redhat.py
coriolis/tests/osmorphing/netpreserver/test_factory.py
coriolis/tests/osmorphing/netpreserver/test_ifcfg.py
coriolis/tests/osmorphing/netpreserver/test_interfaces.py
coriolis/tests/osmorphing/netpreserver/test_netplan.py
coriolis/tests/osmorphing/netpreserver/test_nmconnection.py
coriolis/tests/osmorphing/test_base.py
coriolis/tests/osmorphing/test_debian.py
coriolis/tests/osmorphing/test_redhat.py

- Adds method in `base.py` for preserving Static IPs based on the networking used by the Linux OS
- Changes `redhat.py` and `debian.py` to use the method from `base.py`

Add Static Ip preservation

---

coriolis/osmorphing/osmount/windows.py
coriolis/tests/osmorphing/osmount/test_windows.py

This patch makes sure that the read-only and nodefaultdriveletter flags get disabled before bringing the disks online, thus making sure that disks are always initialized before looking for the root partition.

Fix Windows OSMount when migrating read-only disks.
